services:
  - type: web
    name: taskflow
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerCommand: ./docker/render-start.sh
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: log
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info

databases:
  - name: taskflow-db
    databaseName: taskflow
    user: taskflow
    plan: free
    region: singapore
